In [3]:

import numpy as np
a = np.array([7,2,9,10])
a.shape

(4,)

In [5]:
a = [1,2,3]
type(a)

list

In [6]:
a = np.array([1,2,3])
type(a)

numpy.ndarray

In [8]:
import numpy as np
arr = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
arr

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [18]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [19]:
%timeit my_arr2 = my_arr * 2

1.81 ms ± 152 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [20]:
%timeit my_list2 = [x * 2 for x in my_list]

129 ms ± 19.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [21]:
a = np.array([1,2,3])
data = np.array([[1.5, -0.1, 3], 
                  [0, -3, 6.5]])

In [23]:
print(a.shape)
print(data.shape)

(3,)
(2, 3)


In [24]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [25]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [26]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [27]:
data.shape

(2, 3)

In [28]:
data.ndim

2

In [29]:
data.dtype

dtype('float64')

In [30]:
data.size

6

## Creating nd Arrays

In [31]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [32]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Special Array Creation

#### Special array creation

* `numpy.zeros` creates an array of zeros with a given length or shape
* `numpy.ones` creates an array of ones with a given length or shape
* `numpy.empty` creates an array without initialized values
* `numpy.arange` creates a range
* Pass a tuple for the shape to create a higher dimensional array

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [35]:
np.empty((2, 3, 2))

array([[[2.56351617e-316, 0.00000000e+000],
        [1.01855798e-312, 9.54898106e-313],
        [1.14587773e-312, 1.03977794e-312]],

       [[1.23075756e-312, 1.14587773e-312],
        [1.03977794e-312, 9.76118064e-313],
        [1.01855798e-312, 1.90979621e-312]]])

In [36]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
arr2d = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr2d[0][1]

2

In [41]:
arr2d[0,1]

2

In [42]:
samples = np.random.standard_normal(size=(4, 4))
samples


array([[-1.23901599, -0.07426508, -0.25229338,  0.84597577],
       [-0.15696489,  0.61206898, -0.26028082, -0.68835011],
       [-0.08446891,  0.49833248,  0.54262587, -0.89233955],
       [-1.11847731, -0.98132419,  0.03103233, -1.42944327]])

In [43]:
# seed` determines initial state of generator

rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2, 3))
data


array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465]])

In [44]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [45]:
result = [(x if c else y)
  for x, y, c in zip(xarr, yarr, cond)]

result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [46]:


result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [47]:
arr = rng.standard_normal((4,4))
arr

array([[-1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306],
       [ 2.34740965,  0.96849691, -0.75938718,  0.90219827],
       [-0.46695317, -0.06068952,  0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899,  1.32229806, -0.29969852]])

In [48]:
np.where(arr > 0, 2, -2)

array([[-2,  2,  2, -2],
       [ 2,  2, -2,  2],
       [-2, -2,  2, -2],
       [ 2,  2,  2, -2]])

In [49]:
# set only positive to 2
np.where(arr > 0,2,arr)

array([[-1.3677927 ,  2.        ,  2.        , -1.95286306],
       [ 2.        ,  2.        , -0.75938718,  2.        ],
       [-0.46695317, -0.06068952,  2.        , -1.25666813],
       [ 2.        ,  2.        ,  2.        , -0.29969852]])

In [51]:
arr = rng.standard_normal((5, 4))
arr

array([[ 0.90291934, -1.62158273, -0.15818926,  0.44948393],
       [-1.34360107, -0.08168759,  1.72473993,  2.61815943],
       [ 0.77736134,  0.8286332 , -0.95898831, -1.20938829],
       [-1.41229201,  0.54154683,  0.7519394 , -0.65876032],
       [-1.22867499,  0.25755777,  0.31290292, -0.13081169]])

In [52]:
arr.mean()

0.018063390847970272

In [53]:
np.mean(arr)

0.018063390847970272

In [54]:
arr.mean(axis=1)

array([-0.10684218,  0.72940267, -0.14059552, -0.19439153, -0.1972565 ])

In [55]:
arr.mean(axis=0)

array([-0.46085748, -0.01510651,  0.33448093,  0.21373661])